import { useQuery } from "@tanstack/react-query";
import { Link, NavLink, Route, Routes, useParams } from "react-router-dom";
import { create } from "zustand";
import type { AgentDescriptor, PipelineSnapshot, ProjectSnapshot, TaskSnapshot, FactoryEvent } from "@shared";

type Api<T> = Promise<T>; const get = <T,>(url: string): Api<T> => fetch(url).then(async r => { if (!r.ok) throw new Error("Not available"); return r.json() as Promise<T>; });
const useOffice = create<{ events: FactoryEvent[]; connected: boolean; setEvents: (events: FactoryEvent[]) => void; setConnected: (value: boolean) => void }>(set => ({ events: [], connected: false, setEvents: events => set({ events }), setConnected: connected => set({ connected }) }));
function useEvents() { const setEvents = useOffice(s => s.setEvents); const setConnected = useOffice(s => s.setConnected); useQuery({ queryKey: ["events"], queryFn: async () => { const source = new EventSource("/api/events"); source.onopen = () => setConnected(true); source.onerror = () => setConnected(false); source.addEventListener("factory", event => setEvents([JSON.parse((event as MessageEvent).data), ...useOffice.getState().events].slice(0, 50))); return true; }, staleTime: Infinity }); }
const Badge = ({ value }: { value?: string }) => <span className={`badge ${value ?? "unknown"}`}>{value ?? "Unknown"}</span>;
const Stat = ({ label, value, hint }: { label: string; value: string | number; hint?: string }) => <div className="stat"><span>{label}</span><strong>{value}</strong>{hint && <small>{hint}</small>}</div>;
function Shell({ children }: { children: React.ReactNode }) { useEvents(); const connected = useOffice(s => s.connected); return <div className="shell"><aside><div className="brand"><i>◈</i><span>VISUAL<br/>OFFICE</span></div><nav>{[["/dashboard","Control room"],["/projects","Projects"],["/agents","Agents"]].map(([to,label]) => <NavLink key={to} to={to}>{label}</NavLink>)}</nav><div className="read-only"><span className={connected ? "dot online" : "dot"}/>{connected ? "Live observer" : "Connecting"}<small>Read-only mode</small></div></aside><main>{children}</main></div>; }
function Dashboard() { const pipelines = useQuery({ queryKey:["pipelines"], queryFn: () => get<{pipelines: PipelineSnapshot[]}>("/api/pipelines") }); const projects = useQuery({ queryKey:["projects"], queryFn: () => get<{projects: ProjectSnapshot[]}>("/api/projects") }); const agents = useQuery({ queryKey:["agents"], queryFn: () => get<{agents: AgentDescriptor[]}>("/api/agents") }); const events = useOffice(s => s.events); const running = pipelines.data?.pipelines.filter(p => p.status === "running") ?? []; return <Shell><header><div><p className="eyebrow">Factory observability</p><h1>Control room</h1></div><Badge value="read-only"/></header><section className="stats"><Stat label="Active pipelines" value={running.length}/><Stat label="Projects discovered" value={projects.data?.projects.length ?? "—"}/><Stat label="Agent definitions" value={agents.data?.agents.length ?? "—"}/><Stat label="Visual QA" value="Not available" hint="Phase 1 interface"/></section><section className="grid two"><Panel title="Pipeline activity" action="View all" to="/projects"><div className="rows">{running.length ? running.map(p => <Link className="row" to={`/pipelines/${p.id}`} key={p.id}><span><b>{p.goal || "Unnamed pipeline"}</b><small>{p.project || "Unknown project"}</small></span><span><Badge value={p.status}/><small>Step: {p.currentStepId ?? "Unknown"}</small></span></Link>) : <Empty text="No active pipelines reported by Factory."/>}</div></Panel><Panel title="Recent events">{events.length ? <div className="events">{events.slice(0,8).map(e => <div key={e.id}><span className={`dot ${e.severity}`}/><span>{e.type}</span><small>{new Date(e.occurredAt).toLocaleTimeString()}</small></div>)}</div> : <Empty text="Waiting for real Factory file changes."/>}</Panel></section><section className="grid two"><Panel title="Active agents">{running.length ? running.map(p => { const step = p.steps.find(s => s.id === p.currentStepId); return <div className="agent-line" key={p.id}><i>◉</i><span>{step?.agent ?? "Unknown"}<small>{step?.role ?? "Current role unavailable"}</small></span><Badge value="running"/></div>; }) : <Empty text="No active agents."/>}</Panel><Panel title="Recent pipelines">{pipelines.data?.pipelines.length ? <div className="rows">{pipelines.data.pipelines.slice(0,6).map(p => <Link className="row" to={`/pipelines/${p.id}`} key={p.id}><span><b>{p.goal || "Unnamed pipeline"}</b><small>{p.type} · {p.startedAt ? new Date(p.startedAt).toLocaleString() : "Unknown"}</small></span><Badge value={p.status}/></Link>)}</div> : <Empty text="No pipeline snapshots found."/>}</Panel></section></Shell>; }
function Panel({ title, children, action, to }: { title:string; children:React.ReactNode; action?:string; to?:string }) { return <section className="panel"><div className="panel-title"><h2>{title}</h2>{action && to && <Link to={to}>{action} →</Link>}</div>{children}</section>; } function Empty({text}:{text:string}) { return <div className="empty">{text}</div>; }
function Projects() { const q = useQuery({queryKey:["projects"],queryFn:()=>get<{projects:ProjectSnapshot[]}>("/api/projects")}); return <Shell><header><div><p className="eyebrow">Allowlisted Factory workspaces</p><h1>Projects</h1></div></header><section className="panel table">{q.data?.projects.length ? q.data.projects.map(p => <Link to={`/projects/${p.id}`} key={p.id} className="table-row"><span><b>{p.name}</b><small>{p.path || "Path not available"}</small></span><span>{p.pipelineType}</span><span>{p.currentStepId ?? "Unknown"}</span><span>{p.progress.complete}/{p.progress.total || "Unknown"}</span><Badge value={p.status}/></Link>) : <Empty text="No projects have task or pipeline data."/>}</section></Shell>; }
function Project() { const {id=""}=useParams(); const q=useQuery({queryKey:["projects"],queryFn:()=>get<{projects:ProjectSnapshot[]}>("/api/projects")}); const t=useQuery({queryKey:["tasks",id],queryFn:()=>get<{tasks:TaskSnapshot[]}>(`/api/projects/${encodeURIComponent(id)}/tasks`)}); const project=q.data?.projects.find(p=>p.id===id); return <Shell><header><div><p className="eyebrow">{project?.path || "Path not available"}</p><h1>{project?.name || "Unknown project"}</h1></div><Badge value={project?.status}/></header><section className="stats"><Stat label="Pipeline" value={project?.pipelineType ?? "Unknown"}/><Stat label="Current step" value={project?.currentStepId ?? "Unknown"}/><Stat label="Build" value="Unknown"/><Stat label="QA" value="Not available"/></section><Panel title="Tasks">{t.data?.tasks.length ? <div className="rows">{t.data.tasks.map(task=><div className="row" key={task.id}><span><b>{task.title}</b><small>{task.agent ?? "Unknown agent"} · {task.role}</small></span><span><Badge value={task.status}/><small>Attempt {task.attempts} · {task.model ?? "Unknown model"}</small></span></div>)}</div> : <Empty text="No task snapshot is available for this project."/>}</Panel></Shell>; }
function Agents() { const q=useQuery({queryKey:["agents"],queryFn:()=>get<{agents:AgentDescriptor[]}>("/api/agents")}); return <Shell><header><div><p className="eyebrow">Project-local OpenCode definitions</p><h1>Agents</h1></div></header><section className="agent-grid">{q.data?.agents.map(agent=><article key={agent.name}><i>◇</i><h2>{agent.name}</h2><p>{agent.description ?? "Description not available."}</p><dl><dt>Role</dt><dd>{agent.role}</dd><dt>Status</dt><dd>Unknown</dd><dt>Model</dt><dd>Unknown</dd><dt>Permissions</dt><dd>{agent.canEdit === undefined ? "Unknown" : agent.canEdit ? "Can edit" : "Read-only"}</dd></dl></article>) ?? <Empty text="No agent definitions found."/>}</section></Shell>; }
function Pipeline() { const {id=""}=useParams(); const q=useQuery({queryKey:["pipeline",id],queryFn:()=>get<{pipeline:PipelineSnapshot}>(`/api/pipelines/${encodeURIComponent(id)}`)}); const p=q.data?.pipeline; return <Shell><header><div><p className="eyebrow">{p?.type ?? "Unknown"} pipeline · {p?.project || "Unknown project"}</p><h1>{p?.goal || "Pipeline not available"}</h1></div><Badge value={p?.status}/></header><Panel title="Pipeline steps">{p ? <div className="timeline">{p.steps.map(step=><div className="step" key={step.id}><span className={`step-dot ${step.status}`}/><div><b>{step.title ?? step.id}</b><small>{step.id} · {step.role ?? "Unknown role"} · {step.agent ?? "Unknown agent"}</small></div><div><Badge value={step.status}/><small>Attempt {step.attempt ?? "Unknown"} · {step.model ?? "Unknown model"}</small></div></div>)}</div> : <Empty text="Pipeline snapshot not available."/>}</Panel></Shell>; }
export function App(){return <Routes><Route path="*" element={<Dashboard/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/projects" element={<Projects/>}/><Route path="/projects/:id" element={<Project/>}/><Route path="/agents" element={<Agents/>}/><Route path="/pipelines/:id" element={<Pipeline/>}/></Routes>;}
