import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { FactoryAdapter } from "../backend/src/factory-adapter.js";
import { createApp } from "../backend/src/app.js";
import { normalizePipeline, normalizeTasks } from "../backend/src/events.js";

const fixture = (name: string) => readFile(path.join(import.meta.dirname, "fixtures", name), "utf8");
const roots: string[] = [];
async function factory() { const root = await mkdtemp(path.join(tmpdir(), "visual-office-")); roots.push(root); await mkdir(path.join(root,"outputs","pipelines"),{recursive:true}); await mkdir(path.join(root,"tasks","project-fixture-game"),{recursive:true}); await mkdir(path.join(root,"agents","opencode"),{recursive:true}); await writeFile(path.join(root,"outputs","pipelines","game-fixture1.json"),await fixture("pipeline.json")); await writeFile(path.join(root,"tasks","project-fixture-game","tasks.json"),await fixture("tasks.json")); await writeFile(path.join(root,"agents","opencode","tester.md"),await fixture("tester.md")); return root; }
afterEach(async()=>{ await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true}))); });

describe("FactoryAdapter",()=>{
  it("parses a current pipeline snapshot and safely strips unknown fields",async()=>{const root=await factory();const a=new FactoryAdapter({factoryRoot:root});const [p]=await a.listPipelines();expect(p.id).toBe("game-fixture1");expect(p.status).toBe("running");expect(p.entries[0].output).toBe("Safe agent report");expect((p as Record<string,unknown>).futureFactoryField).toBeUndefined();});
  it("parses current task JSON and attempt history",async()=>{const root=await factory();const tasks=await new FactoryAdapter({factoryRoot:root}).getTasks("fixture-game");expect(tasks?.[0].model).toBe("opencode/mimo-v2.5-free");expect(tasks?.[0].attemptHistory?.[0].attempt).toBe(1);});
  it("handles malformed JSON without throwing",async()=>{const root=await factory();await writeFile(path.join(root,"outputs","pipelines","bad.json"),"{");const a=new FactoryAdapter({factoryRoot:root});await expect(a.listPipelines()).resolves.toHaveLength(1);expect(a.consumeDiagnostics().some(d=>d.source.endsWith("bad.json"))).toBe(true);});
  it("parses agent metadata and discovers projects",async()=>{const root=await factory();const a=new FactoryAdapter({factoryRoot:root});expect((await a.getAgent("tester"))?.canEdit).toBe(false);expect((await a.listProjects())[0].id).toBe("fixture-game");});
});
describe("API and events",()=>{
  it("serves health, pipelines and agents",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const health=await app.inject("/api/health");const pipelines=await app.inject("/api/pipelines");const agents=await app.inject("/api/agents");expect(health.statusCode).toBe(200);expect(JSON.parse(pipelines.body).pipelines[0].id).toBe("game-fixture1");expect(JSON.parse(agents.body).agents[0].name).toBe("tester");await app.close();});
  it("serves diagnostics, visual qa, and hermes stubs",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const diagnostics=await app.inject("/api/diagnostics");const visualQa=await app.inject("/api/visual-qa/status");const hermes=await app.inject("/api/hermes/status");expect(diagnostics.statusCode).toBe(200);expect(visualQa.statusCode).toBe(200);expect(JSON.parse(visualQa.body).visualQa.available).toBe(true);expect(JSON.parse(hermes.body).hermes.available).toBe(false);await app.close();});
  it("serves task detail with validated ids",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const tasks=JSON.parse((await app.inject("/api/projects/fixture-game/tasks")).body).tasks;const task=await app.inject(`/api/projects/fixture-game/tasks/${tasks[0].id}`);expect(task.statusCode).toBe(200);expect((await app.inject("/api/projects/../etc/tasks")).statusCode).toBe(404);await app.close();});
  it("has an SSE connection endpoint",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});await app.listen({host:"127.0.0.1",port:0});const address=app.server.address();const port=typeof address==="object"&&address?address.port:0;const controller=new AbortController();const response=await fetch(`http://127.0.0.1:${port}/api/events`,{signal:controller.signal});expect(response.headers.get("content-type")).toContain("text/event-stream");controller.abort();await app.close();});
  it("exposes recent events over REST",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:true});await app.ready();const recent=await app.inject("/api/events/recent");expect(recent.statusCode).toBe(200);expect(Array.isArray(JSON.parse(recent.body).events)).toBe(true);await app.close();});
  it("normalizes real snapshot deltas",async()=>{const root=await factory();const [next]=await new FactoryAdapter({factoryRoot:root}).listPipelines();expect(normalizePipeline(undefined,next).some(e=>e.type==="pipeline.started")).toBe(true);const tasks=await new FactoryAdapter({factoryRoot:root}).getTasks("fixture-game")??[];expect(normalizeTasks("fixture-game",[],tasks).some(e=>e.type==="task.created")).toBe(true);});
  it("does not expose arbitrary filesystem or shell endpoints",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});expect((await app.inject("/api/files?path=/etc/passwd")).statusCode).toBe(404);expect((await app.inject({method:"POST",url:"/api/shell"})).statusCode).toBe(404);await app.close();});
});
describe("Mission API",()=>{
  it("lists missions (empty)",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const res=await app.inject("/api/missions");expect(res.statusCode).toBe(200);expect(JSON.parse(res.body).missions).toEqual([]);await app.close();});
  it("creates a mission with valid goal",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const res=await app.inject({method:"POST",url:"/api/missions",payload:{goal:"Build a platformer game"}});expect(res.statusCode).toBe(201);const body=JSON.parse(res.body);expect(body.mission.id).toMatch(/^mission-/);expect(body.mission.goal).toBe("Build a platformer game");expect(body.mission.status).toBe("draft");await app.close();});
  it("rejects empty goal",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const res=await app.inject({method:"POST",url:"/api/missions",payload:{goal:""}});expect(res.statusCode).toBe(400);const body=JSON.parse(res.body);expect(body.error || body.details).toBeDefined();await app.close();});
  it("rejects invalid project id",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const res=await app.inject({method:"POST",url:"/api/missions",payload:{goal:"Build something",projectId:"nonexistent"}});expect(res.statusCode).toBe(400);expect(JSON.parse(res.body).error).toMatch(/allowlist|not found|invalid/i);await app.close();});
  it("rejects malformed JSON body",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const res=await app.inject({method:"POST",url:"/api/missions",headers:{"content-type":"application/json"},payload:"not json"});expect(res.statusCode).toBeGreaterThanOrEqual(400);await app.close();});
  it("gets mission detail",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const create=await app.inject({method:"POST",url:"/api/missions",payload:{goal:"Test mission"}});const id=JSON.parse(create.body).mission.id;const res=await app.inject(`/api/missions/${id}`);expect(res.statusCode).toBe(200);expect(JSON.parse(res.body).mission.mission.goal).toBe("Test mission");await app.close();});
  it("returns 404 for unknown mission",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const res=await app.inject("/api/missions/mission-nonexistent123");expect(res.statusCode).toBe(404);await app.close();});
  it("starts a mission",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const create=await app.inject({method:"POST",url:"/api/missions",payload:{goal:"Build a game"}});const id=JSON.parse(create.body).mission.id;const res=await app.inject({method:"POST",url:`/api/missions/${id}/start`});expect(res.statusCode).toBe(200);const body=JSON.parse(res.body);expect(["running","planned"]).toContain(body.mission.mission.status);await app.close();});
  it("does not accept shell commands in mission creation",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const res=await app.inject({method:"POST",url:"/api/missions",payload:{goal:"Run rm -rf /"}});expect(res.statusCode).toBe(201);const body=JSON.parse(res.body);expect(body.mission.goal).toBe("Run rm -rf /");await app.close();});
  it("mission events do not leak secrets in SSE",async()=>{const root=await factory();const app=createApp({factoryRoot:root,startMonitor:false});const res=await app.inject("/api/events/recent");const events=JSON.parse(res.body).events;const missionEvents=events.filter((e:{type:string})=>e.type.startsWith("mission."));for(const evt of missionEvents){expect(JSON.stringify(evt)).not.toMatch(/sk-[A-Za-z0-9]{12,}/);expect(JSON.stringify(evt)).not.toMatch(/api[_-]?key/i);}await app.close();});
});
